### Задание 1. Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log (как вариант - использовать np.clip или np.where).

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [2]:
# Данные из ноутбука

X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],  
              [500, 700, 750, 600, 1450,        
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 1, 3, 3, 1, 2]], 
              dtype = np.float64).T 

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1])

In [3]:
# Стандартизация

def standard_scale(x: np.ndarray) -> np.ndarray:
    s = (x - x.mean()) / x.std()
    return s

In [4]:
# Сигмоида

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [5]:
# Логистическая ф-ция потерь

def calc_logloss(y, y_pred):
    y_pred = np.clip(y_pred, a_min = 1e-10, a_max = 1 - 1e-10)
    err = np.mean(- y * np.log(y_pred) - (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [6]:
calc_logloss(y=0, y_pred=1)

23.02585084720009

### Задание 2. На данных из урока изучите влияние гиперпараметров на ошибку алгоритма.

In [14]:
# Логистическая регрессия

def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    w = np.random.randn(X.shape[1])
    n = X.shape[0]
    
    for i in range(1, iterations + 1):
        z = np.dot(X, w) # log(p/(1-p))
        y_pred = sigmoid(z) # p [0, 1]
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/n * np.dot((y_pred - y), X))
        
        if i % (iterations / 10) == 0:
            print(i, w, err)
    
    return w

In [16]:
# Создаем копию, стандартизируем

X_st = X.copy()
X_st[:, 2] = standard_scale(X[:, 2])
X_st[:, 2]

array([-0.97958969, -0.56713087, -0.46401617, -0.77336028,  0.97958969,
       -0.36090146,  1.08270439,  2.11385144, -1.08270439,  0.05155735])

In [17]:
w = eval_model(X_st, y, 1000, 1e-1)

100 [-0.29848458 -0.72686866  1.06314016  1.39690737] 0.5235767485993659
200 [-0.64245884 -0.81575707  1.11680356  1.72702881] 0.4995552177931558
300 [-0.95659618 -0.87689661  1.10232809  2.00636498] 0.4814150662731217
400 [-1.25432451 -0.91736333  1.05455726  2.24457861] 0.4664467561141666
500 [-1.5375957  -0.94440497  0.98735478  2.45373702] 0.4535011239613406
600 [-1.80755433 -0.96270374  0.90904148  2.64183838] 0.44201377632900957
700 [-2.06512906 -0.9753011   0.82492184  2.81420765] 0.4316738793739682
800 [-2.31113497 -0.98420861  0.73842971  2.97447927] 0.42228858977623346
900 [-2.54631605 -0.99077064  0.65178699  3.12518707] 0.4137239929669819
1000 [-2.77136565 -0.99588853  0.56641089  3.26813012] 0.4058781527072773


In [18]:
w = eval_model(X_st, y, 2000, 2e-1)

200 [-1.25475108 -0.91775717  1.05510451  2.24546166] 0.4665550707802967
400 [-2.31172961 -0.98436104  0.73845826  2.97508008] 0.4223547031209668
600 [-3.19432839 -1.00405047  0.40240132  3.53607427] 0.3920665710307173
800 [-3.94367938 -1.01887148  0.10965898  4.01686396] 0.37003626740456036
1000 [-4.59167819 -1.03602019 -0.13853495  4.44549975] 0.35335824231974877
1200 [-5.16236384 -1.05563116 -0.35118429  4.83483613] 0.34026146208644537
1400 [-5.67340922 -1.07682169 -0.53678932  5.19288695] 0.3296385294100062
1600 [-6.1377458  -1.09885773 -0.70177395  5.52546775] 0.32077945191674806
1800 [-6.56490521 -1.12126342 -0.85078204  5.83703416] 0.3132156797332823
2000 [-6.96200326 -1.1437517  -0.98717545  6.13106725] 0.3066288709443726


In [19]:
w = eval_model(X_st, y, 2000, 3e-1)

200 [-1.80869507 -0.96324939  0.90956419  2.64339334] 0.4421769355650185
400 [-3.19509128 -1.00410899  0.40218374  3.53663094] 0.3921061065318555
600 [-4.27946848 -1.02711567 -0.01977978  4.23725427] 0.3611798085105197
800 [-5.16314175 -1.05565711 -0.35147622  4.83536803] 0.34027386616759003
1000 [-5.91150573 -1.08780162 -0.62180568  5.36258931] 0.3250299580423658
1200 [-6.5656299  -1.12130072 -0.85103645  5.83756294] 0.31322088669455994
1400 [-7.15171659 -1.15501146 -1.05168024  6.27291288] 0.3036332362553184
1600 [-7.68700661 -1.18841682 -1.23160758  6.67747871] 0.2955626579291414
1800 [-8.18321983 -1.22129592 -1.39597104  7.05757416] 0.2885766702286493
2000 [-8.64856652 -1.25356526 -1.54827565  7.41779614] 0.2823966216143977


In [20]:
w = eval_model(X_st, y, 10000, 1.5)

1000 [-14.33659933  -1.70691746  -3.32731109  11.96451936] 0.22403801111581356
2000 [-20.4029256   -2.2302234   -5.14707419  16.88431408] 0.18056136013262858
3000 [-24.9710286   -2.63165769  -6.48985807  20.58832391] 0.15606292777290554
4000 [-28.64763931  -2.95640633  -7.55872608  23.56418832] 0.14026159180414505
5000 [-31.73627959  -3.22912056  -8.45086017  26.05879037] 0.12914713922913865
6000 [-34.41139591  -3.46447278  -9.22067269  28.21434743] 0.12083294246934753
7000 [-36.78148572  -3.67178761  -9.90139217  30.1193971 ] 0.11432304389900064
8000 [-38.91815874  -3.85731491 -10.51464854  31.832412  ] 0.10904458548212229
9000 [-40.8709429   -4.02542927 -11.07523769  33.39385591] 0.10464537539417966
10000 [-42.6754094   -4.17930416 -11.59368902  34.83280672] 0.10089708998179552


Значение ошибки = $0.3$, при альфа = $0.2$, кол-во итераций = $2000$. Первые три веса уменьшились, а последний вырос.

Значение ошибки = $0.1$, при альфа = $1.5$, кол-во итераций = $10000$. Первые три веса сильно уменьшились, а последний сильно вырос.

### Задание 3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса "1". На вход функции подаются значения признаков Х и веса, которые уже посчитаны функцией eval_model.

In [21]:
def calc_pred_proba(w, X):
    return sigmoid(np.dot(X_st, w))
calc_pred_proba(w, X_st)

array([0.33965128, 0.00429172, 1.        , 0.04496738, 0.9566957 ,
       0.02512555, 1.        , 0.01123562, 0.62963032, 0.99999999])

### Задание 4. Создайте функцию calc_pred, возвращающую предсказанные классы (0 или 1). На вход функции подаются значения признаков Х и веса, которые уже посчитаны функцией eval_model, а также порог вероятности.

In [23]:
def calc_pred(w, X):
  pred = sigmoid(np.dot(X_st, w))
  pred.round(2)
  return np.where(pred > 0.5, 1, 0)
calc_pred(w, X_st)

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1])